name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn
          always-auth: true
          registry-url: https://registry.npmjs.org

      - run: yarn install
      - run: yarn build

      - name: Publish to NPM
        run: yarn publish --tag latest --access public
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
